import React, { useState, useEffect } from 'react';
import { UserLicenseState, SubscriptionTier } from '../monetization/types';
import { setSubscriptionTier, resetUsage, setScanUsageCount } from '../monetization/licenseStore';
import { UserSettings } from '../settings/settingsStore';
import { LogEntry, LogLevel } from './types';
import {
  getLogs,
  clearLogs,
  addLog,
  buildDiagnosticReport,
  downloadDiagnosticReport,
  copyDiagnosticReportToClipboard,
  logInfo,
  logWarn,
  logError
} from './loggerService';
import {
  X,
  ShieldCheck,
  Zap,
  Terminal,
  Download,
  Copy,
  Trash2,
  Check,
  RefreshCw,
  Sliders,
  FileText,
  Send,
  FileSpreadsheet,
  AlertTriangle,
  Info,
  Bug,
  Search,
  ExternalLink,
  Lock,
  Key
} from 'lucide-react';
import {
  lockAdminSession,
  updateAdminPasscode,
  resetAdminPasscodeToDefault
} from './adminAuthService';

interface AdminPanelModalProps {
  isOpen: boolean;
  onClose: () => void;
  license: UserLicenseState;
  settings: UserSettings;
  onLicenseUpdated: (newLicense: UserLicenseState) => void;
  onTriggerPdfAudit?: () => void;
  onTriggerCrmSync?: () => void;
  onTriggerExport?: () => void;
  onLockSession?: () => void;
  savedProspectsCount?: number;
}

export const AdminPanelModal: React.FC<AdminPanelModalProps> = ({
  isOpen,
  onClose,
  license,
  settings,
  onLicenseUpdated,
  onTriggerPdfAudit,
  onTriggerCrmSync,
  onTriggerExport,
  onLockSession,
  savedProspectsCount = 0
}) => {
  const [activeTab, setActiveTab] = useState<'plans' | 'logs'>('plans');
  const [logs, setLogs] = useState<LogEntry[]>([]);
  const [logFilter, setLogFilter] = useState<LogLevel | 'ALL'>('ALL');
  const [searchQuery, setSearchQuery] = useState('');
  const [copied, setCopied] = useState(false);
  const [actionFeedback, setActionFeedback] = useState<string | null>(null);

  // Security & Passcode state
  const [currentPass, setCurrentPass] = useState('');
  const [newPass, setNewPass] = useState('');
  const [securityStatus, setSecurityStatus] = useState<{ type: 'success' | 'error'; msg: string } | null>(null);
  const [isUpdatingPass, setIsUpdatingPass] = useState(false);

  useEffect(() => {
    if (isOpen) {
      loadLogs();
    }
  }, [isOpen]);

  const loadLogs = async () => {
    const list = await getLogs();
    setLogs(list);
  };

  if (!isOpen) return null;

  const showFeedback = (msg: string) => {
    setActionFeedback(msg);
    setTimeout(() => setActionFeedback(null), 2500);
  };

  const handleSelectTier = async (tier: SubscriptionTier) => {
    const updated = await setSubscriptionTier(tier);
    onLicenseUpdated(updated);
    logInfo('ADMIN', `Manually switched subscription tier to [${tier.toUpperCase()}]`);
    showFeedback(`Switched plan to ${tier.toUpperCase()}`);
    loadLogs();
  };

  const handleResetScans = async () => {
    const updated = await resetUsage();
    onLicenseUpdated(updated);
    logInfo('ADMIN', 'Manually reset monthly scans count to 0');
    showFeedback('Monthly scan count reset to 0');
    loadLogs();
  };

  const handleSetScansLimit = async (count: number) => {
    const updated = await setScanUsageCount(count);
    onLicenseUpdated(updated);
    logInfo('ADMIN', `Set monthly scan usage count to ${count}`);
    showFeedback(`Scans used set to ${count}`);
    loadLogs();
  };

  const handleClearLogs = async () => {
    await clearLogs();
    setLogs([]);
    showFeedback('System logs cleared');
  };

  const handleDownloadReport = async () => {
    const report = await buildDiagnosticReport(license, settings, savedProspectsCount);
    downloadDiagnosticReport(report);
    logInfo('ADMIN', 'Downloaded full system diagnostic report');
    showFeedback('Diagnostic report downloaded');
    loadLogs();
  };

  const handleCopyReport = async () => {
    const report = await buildDiagnosticReport(license, settings, savedProspectsCount);
    const success = await copyDiagnosticReportToClipboard(report);
    if (success) {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
      showFeedback('Diagnostic report copied to clipboard');
    }
  };

  const handleSimulateTestError = async () => {
    logError(
      'DIAGNOSTICS_TEST',
      'Test simulated error generated by Admin Panel',
      new Error('Synthetic verification error for diagnostic pipeline testing'),
      { simulated: true, timestamp: new Date().toISOString() },
      'https://example-test-site.com'
    );
    showFeedback('Simulated test error recorded to logs');
    loadLogs();
  };

  const handleLockSession = async () => {
    await lockAdminSession();
    onLockSession?.();
    onClose();
  };

  const handleUpdatePasscode = async () => {
    if (!currentPass || !newPass) {
      setSecurityStatus({ type: 'error', msg: 'Both current and new passcodes are required.' });
      return;
    }
    setIsUpdatingPass(true);
    setSecurityStatus(null);
    const res = await updateAdminPasscode(currentPass, newPass);
    setIsUpdatingPass(false);
    if (res.success) {
      setSecurityStatus({ type: 'success', msg: 'Admin passcode updated successfully.' });
      setCurrentPass('');
      setNewPass('');
      loadLogs();
    } else {
      setSecurityStatus({ type: 'error', msg: res.error || 'Failed to update passcode.' });
    }
  };

  const handleResetPasscodeDefault = async () => {
    await resetAdminPasscodeToDefault();
    setSecurityStatus({ type: 'success', msg: 'Passcode reset to system default (admin2026).' });
    setCurrentPass('');
    setNewPass('');
    loadLogs();
  };

  const filteredLogs = logs.filter((log) => {
    const matchesLevel = logFilter === 'ALL' || log.level === logFilter;
    const matchesSearch =
      !searchQuery ||
      log.message.toLowerCase().includes(searchQuery.toLowerCase()) ||
      log.context.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (log.url && log.url.toLowerCase().includes(searchQuery.toLowerCase()));
    return matchesLevel && matchesSearch;
  });

  const errorCount = logs.filter((l) => l.level === 'ERROR').length;
  const warnCount = logs.filter((l) => l.level === 'WARN').length;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 bg-slate-950/80 backdrop-blur-xs animate-in fade-in duration-150">
      <div className="bg-slate-900 border border-slate-800 rounded-xl w-full max-w-xl shadow-2xl flex flex-col max-h-[92vh] overflow-hidden text-slate-200">
        
        {/* Header */}
        <div className="p-4 border-b border-slate-800 flex items-center justify-between bg-slate-950/70">
          <div className="flex items-center gap-2.5">
            <div className="p-2 bg-emerald-950/70 border border-emerald-500/40 rounded-lg text-emerald-400">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-semibold text-white text-sm">Developer & Admin Sandbox</h3>
                <span className="px-1.5 py-0.5 text-[9px] font-bold bg-emerald-950 text-emerald-300 border border-emerald-500/30 rounded uppercase tracking-wider">
                  DEV MODE
                </span>
              </div>
              <p className="text-[11px] text-slate-400">
                Test premium tiers, simulate usage limits, and inspect live diagnostic error logs
              </p>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleLockSession}
              className="px-2.5 py-1 bg-slate-950 hover:bg-rose-950/70 border border-slate-800 hover:border-rose-500/50 text-slate-300 hover:text-rose-300 rounded-lg text-[10px] font-semibold flex items-center gap-1.5 transition cursor-pointer"
              title="Lock admin session immediately"
            >
              <Lock className="w-3 h-3 text-rose-400" />
              <span>Lock Admin</span>
            </button>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-white p-1 rounded-md hover:bg-slate-800 transition cursor-pointer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Tab Bar */}
        <div className="flex border-b border-slate-800 bg-slate-950/40 px-4 pt-2">
          <button
            onClick={() => setActiveTab('plans')}
            className={`flex items-center gap-1.5 pb-2 px-3 text-xs font-semibold border-b-2 transition cursor-pointer ${
              activeTab === 'plans'
                ? 'border-cyan-400 text-cyan-300'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Sliders className="w-3.5 h-3.5" />
            <span>Plan & Feature Simulator</span>
          </button>
          <button
            onClick={() => {
              setActiveTab('logs');
              loadLogs();
            }}
            className={`flex items-center gap-1.5 pb-2 px-3 text-xs font-semibold border-b-2 transition cursor-pointer ${
              activeTab === 'logs'
                ? 'border-cyan-400 text-cyan-300'
                : 'border-transparent text-slate-400 hover:text-slate-200'
            }`}
          >
            <Terminal className="w-3.5 h-3.5" />
            <span>Live Logs & Diagnostics</span>
            {errorCount > 0 && (
              <span className="px-1.5 py-0.2 bg-rose-950 text-rose-300 border border-rose-600/40 rounded-full text-[9px] font-bold">
                {errorCount}
              </span>
            )}
          </button>
        </div>

        {/* Action Feedback Toast */}
        {actionFeedback && (
          <div className="bg-cyan-950/80 border-b border-cyan-500/40 px-4 py-1.5 text-xs text-cyan-200 flex items-center gap-2 animate-in fade-in">
            <Check className="w-3.5 h-3.5 text-cyan-400" />
            <span>{actionFeedback}</span>
          </div>
        )}

        {/* Content Area */}
        <div className="p-4 space-y-4 overflow-y-auto text-xs flex-1">
          
          {/* TAB 1: PLANS & PREMIUM SIMULATOR */}
          {activeTab === 'plans' && (
            <div className="space-y-4">
              
              {/* Active Plan Selector */}
              <div>
                <label className="text-[11px] font-semibold text-slate-300 mb-2 block">
                  Select Active Subscription Tier
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { id: 'free', name: 'Free Tier', price: '$0', desc: '5 Scans/mo • Capped Exports' },
                    { id: 'pro', name: 'Pro Plan', price: '$49/mo', desc: 'Unlimited Scans • PDF Audits' },
                    { id: 'agency', name: 'Agency Scale', price: '$119/mo', desc: 'CRM Sync • Whitelabel PDF' }
                  ].map((t) => {
                    const isCurrent = license.tier === t.id;
                    return (
                      <div
                        key={t.id}
                        onClick={() => handleSelectTier(t.id as SubscriptionTier)}
                        className={`p-3 rounded-lg border cursor-pointer transition flex flex-col justify-between ${
                          isCurrent
                            ? 'bg-blue-950/50 border-cyan-400 shadow-xs'
                            : 'bg-slate-950/60 border-slate-800 hover:border-slate-700'
                        }`}
                      >
                        <div>
                          <div className="flex items-center justify-between">
                            <span className="font-bold text-white text-xs">{t.name}</span>
                            {isCurrent && (
                              <span className="text-[9px] px-1 py-0.2 rounded font-bold bg-cyan-950 text-cyan-300 border border-cyan-500/40">
                                ACTIVE
                              </span>
                            )}
                          </div>
                          <div className="text-cyan-400 font-semibold text-[11px] mt-0.5">{t.price}</div>
                        </div>
                        <p className="text-[10px] text-slate-400 mt-2 leading-tight">{t.desc}</p>
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Scan Usage Controls */}
              <div className="bg-slate-950/70 border border-slate-800 rounded-lg p-3 space-y-2">
                <div className="flex items-center justify-between">
                  <span className="font-semibold text-slate-200 text-xs">Monthly Scan Meter Override</span>
                  <span className="text-xs font-mono font-bold text-cyan-400">
                    {license.isPro ? 'Unlimited' : `${license.scansUsedThisMonth} / 10 used`}
                  </span>
                </div>
                <div className="flex gap-2 pt-1">
                  <button
                    onClick={handleResetScans}
                    className="flex-1 py-1.5 px-2 bg-slate-900 hover:bg-slate-800 border border-slate-700 rounded text-slate-300 hover:text-white transition font-medium cursor-pointer"
                  >
                    Reset Scans to 0
                  </button>
                  <button
                    onClick={() => handleSetScansLimit(10)}
                    className="flex-1 py-1.5 px-2 bg-amber-950/50 hover:bg-amber-950/80 border border-amber-600/40 rounded text-amber-300 transition font-medium cursor-pointer"
                  >
                    Set to Limit (10 Scans)
                  </button>
                </div>
              </div>

              {/* 1-Click Feature Testers */}
              <div>
                <label className="text-[11px] font-semibold text-slate-300 mb-2 block">
                  Quick Feature Test Triggers
                </label>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    onClick={() => {
                      onClose();
                      onTriggerPdfAudit?.();
                    }}
                    className="p-2.5 bg-slate-950/70 hover:bg-slate-800 border border-slate-800 rounded-lg flex items-center gap-2 text-left cursor-pointer transition"
                  >
                    <FileText className="w-4 h-4 text-cyan-400 shrink-0" />
                    <div>
                      <div className="font-semibold text-white text-xs">Test 1-Page PDF Audit</div>
                      <div className="text-[10px] text-slate-400">Opens growth audit scorecard</div>
                    </div>
                  </button>

                  <button
                    onClick={() => {
                      onClose();
                      onTriggerCrmSync?.();
                    }}
                    className="p-2.5 bg-slate-950/70 hover:bg-slate-800 border border-slate-800 rounded-lg flex items-center gap-2 text-left cursor-pointer transition"
                  >
                    <Send className="w-4 h-4 text-cyan-400 shrink-0" />
                    <div>
                      <div className="font-semibold text-white text-xs">Test Agency CRM Sync</div>
                      <div className="text-[10px] text-slate-400">Opens GoHighLevel webhook modal</div>
                    </div>
                  </button>

                  <button
                    onClick={() => {
                      onClose();
                      onTriggerExport?.();
                    }}
                    className="p-2.5 bg-slate-950/70 hover:bg-slate-800 border border-slate-800 rounded-lg flex items-center gap-2 text-left cursor-pointer transition"
                  >
                    <FileSpreadsheet className="w-4 h-4 text-emerald-400 shrink-0" />
                    <div>
                      <div className="font-semibold text-white text-xs">Test Bulk Lead Exporter</div>
                      <div className="text-[10px] text-slate-400">Opens Instantly/Excel CSV modal</div>
                    </div>
                  </button>

                  <button
                    onClick={handleSimulateTestError}
                    className="p-2.5 bg-slate-950/70 hover:bg-slate-800 border border-slate-800 rounded-lg flex items-center gap-2 text-left cursor-pointer transition"
                  >
                    <Bug className="w-4 h-4 text-rose-400 shrink-0" />
                    <div>
                      <div className="font-semibold text-white text-xs">Log Simulated Error</div>
                      <div className="text-[10px] text-slate-400">Verifies diagnostics pipeline</div>
                    </div>
                  </button>
                </div>
              </div>

              {/* Admin Security & Master Passcode */}
              <div className="bg-slate-950/70 border border-slate-800 rounded-lg p-3 space-y-2.5">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-1.5 font-semibold text-slate-200 text-xs">
                    <Key className="w-3.5 h-3.5 text-emerald-400" />
                    <span>Admin Security & Master Passcode</span>
                  </div>
                  <span className="text-[10px] text-emerald-400 font-mono">AUTHENTICATED</span>
                </div>

                <p className="text-[10px] text-slate-400 leading-snug">
                  Only administrators with this passcode can unlock the sandbox and inspect live diagnostics.
                </p>

                {securityStatus && (
                  <div className={`p-2 rounded text-[11px] flex items-center gap-1.5 ${
                    securityStatus.type === 'success' 
                      ? 'bg-emerald-950/70 border border-emerald-500/40 text-emerald-300' 
                      : 'bg-rose-950/70 border border-rose-600/40 text-rose-300'
                  }`}>
                    <span>{securityStatus.msg}</span>
                  </div>
                )}

                <div className="grid grid-cols-2 gap-2 pt-1">
                  <div>
                    <label className="block text-[10px] text-slate-400 mb-0.5">Current Passcode</label>
                    <input
                      type="password"
                      placeholder="Current..."
                      value={currentPass}
                      onChange={(e) => setCurrentPass(e.target.value)}
                      className="w-full bg-slate-900 border border-slate-800 rounded px-2 py-1 text-white text-xs font-mono focus:outline-none focus:border-emerald-500"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] text-slate-400 mb-0.5">New Passcode (min 6 chars)</label>
                    <input
                      type="password"
                      placeholder="New..."
                      value={newPass}
                      onChange={(e) => setNewPass(e.target.value)}
                      className="w-full bg-slate-900 border border-slate-800 rounded px-2 py-1 text-white text-xs font-mono focus:outline-none focus:border-emerald-500"
                    />
                  </div>
                </div>

                <div className="flex items-center justify-between gap-2 pt-1">
                  <button
                    type="button"
                    onClick={handleResetPasscodeDefault}
                    className="text-[10px] text-slate-400 hover:text-slate-200 underline cursor-pointer"
                  >
                    Reset to Default (admin2026)
                  </button>
                  <button
                    type="button"
                    disabled={isUpdatingPass}
                    onClick={handleUpdatePasscode}
                    className="px-3 py-1 bg-emerald-600 hover:bg-emerald-500 text-white rounded text-xs font-semibold transition cursor-pointer disabled:opacity-50"
                  >
                    {isUpdatingPass ? 'Updating...' : 'Update Passcode'}
                  </button>
                </div>
              </div>

            </div>
          )}

          {/* TAB 2: LOGS & DIAGNOSTICS */}
          {activeTab === 'logs' && (
            <div className="space-y-3">
              
              {/* Stats Bar */}
              <div className="grid grid-cols-4 gap-2 text-center">
                <div className="p-2 bg-slate-950/80 border border-slate-800 rounded-lg">
                  <div className="text-[10px] text-slate-400">Total Logs</div>
                  <div className="text-sm font-bold text-white font-mono">{logs.length}</div>
                </div>
                <div className="p-2 bg-slate-950/80 border border-slate-800 rounded-lg">
                  <div className="text-[10px] text-rose-400">Errors</div>
                  <div className="text-sm font-bold text-rose-400 font-mono">{errorCount}</div>
                </div>
                <div className="p-2 bg-slate-950/80 border border-slate-800 rounded-lg">
                  <div className="text-[10px] text-amber-400">Warnings</div>
                  <div className="text-sm font-bold text-amber-400 font-mono">{warnCount}</div>
                </div>
                <div className="p-2 bg-slate-950/80 border border-slate-800 rounded-lg">
                  <div className="text-[10px] text-cyan-400">Active Tier</div>
                  <div className="text-sm font-bold text-cyan-300 font-mono uppercase">{license.tier}</div>
                </div>
              </div>

              {/* Action Toolbar */}
              <div className="flex items-center gap-2">
                <div className="relative flex-1">
                  <Search className="w-3.5 h-3.5 absolute left-2.5 top-2.5 text-slate-500" />
                  <input
                    type="text"
                    placeholder="Search logs by message, context, url..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="w-full pl-8 pr-2.5 py-1.5 bg-slate-950 border border-slate-800 rounded-lg text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500"
                  />
                </div>

                <select
                  value={logFilter}
                  onChange={(e) => setLogFilter(e.target.value as any)}
                  className="bg-slate-950 border border-slate-800 rounded-lg px-2 py-1.5 text-xs text-white focus:outline-none"
                >
                  <option value="ALL">All Levels</option>
                  <option value="ERROR">Errors Only</option>
                  <option value="WARN">Warnings Only</option>
                  <option value="INFO">Info Only</option>
                  <option value="DEBUG">Debug Only</option>
                </select>

                <button
                  onClick={handleDownloadReport}
                  className="px-2.5 py-1.5 bg-cyan-600 hover:bg-cyan-500 text-white rounded-lg flex items-center gap-1.5 transition font-semibold cursor-pointer shrink-0"
                  title="Download complete diagnostic report in JSON"
                >
                  <Download className="w-3.5 h-3.5" />
                  <span>Report</span>
                </button>

                <button
                  onClick={handleCopyReport}
                  className="px-2.5 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg flex items-center gap-1.5 transition cursor-pointer shrink-0"
                  title="Copy diagnostic JSON to clipboard"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                  <span>{copied ? 'Copied' : 'Copy'}</span>
                </button>

                <button
                  onClick={handleClearLogs}
                  className="p-1.5 bg-slate-800 hover:bg-rose-950 hover:text-rose-300 text-slate-400 rounded-lg transition cursor-pointer shrink-0"
                  title="Clear all stored logs"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>

              {/* Log Stream */}
              <div className="bg-slate-950 border border-slate-800 rounded-lg max-h-64 overflow-y-auto font-mono text-[11px] p-2 space-y-2">
                {filteredLogs.length === 0 ? (
                  <div className="text-center py-6 text-slate-500">
                    No log records matching your filter.
                  </div>
                ) : (
                  filteredLogs.map((entry) => {
                    const isError = entry.level === 'ERROR';
                    const isWarn = entry.level === 'WARN';
                    const isInfo = entry.level === 'INFO';
                    return (
                      <div
                        key={entry.id}
                        className={`p-2 rounded border ${
                          isError
                            ? 'bg-rose-950/30 border-rose-700/40 text-rose-200'
                            : isWarn
                            ? 'bg-amber-950/30 border-amber-700/40 text-amber-200'
                            : isInfo
                            ? 'bg-cyan-950/20 border-cyan-800/30 text-slate-300'
                            : 'bg-slate-900/50 border-slate-800 text-slate-400'
                        }`}
                      >
                        <div className="flex items-center justify-between text-[10px] text-slate-400 mb-1">
                          <div className="flex items-center gap-1.5">
                            <span
                              className={`px-1 py-0.2 rounded font-bold uppercase ${
                                isError
                                  ? 'bg-rose-950 text-rose-300 border border-rose-600/40'
                                  : isWarn
                                  ? 'bg-amber-950 text-amber-300 border border-amber-600/40'
                                  : isInfo
                                  ? 'bg-cyan-950 text-cyan-300 border border-cyan-600/40'
                                  : 'bg-slate-800 text-slate-400'
                              }`}
                            >
                              {entry.level}
                            </span>
                            <span className="font-semibold text-slate-200">{entry.context}</span>
                          </div>
                          <span>{entry.timestamp.slice(11, 19)}</span>
                        </div>

                        <div className="text-slate-200 whitespace-pre-wrap">{entry.message}</div>

                        {entry.url && (
                          <div className="text-[10px] text-cyan-400/80 truncate mt-1">
                            URL: {entry.url}
                          </div>
                        )}

                        {entry.errorStack && (
                          <pre className="text-[10px] text-rose-400/90 mt-1.5 bg-slate-950 p-1.5 rounded overflow-x-auto whitespace-pre">
                            {entry.errorStack}
                          </pre>
                        )}

                        {entry.details && Object.keys(entry.details).length > 0 && (
                          <pre className="text-[10px] text-slate-400 mt-1 bg-slate-950/80 p-1 rounded overflow-x-auto">
                            {JSON.stringify(entry.details, null, 2)}
                          </pre>
                        )}
                      </div>
                    );
                  })
                )}
              </div>

            </div>
          )}

        </div>

        {/* Footer */}
        <div className="p-3 border-t border-slate-800 bg-slate-950/80 flex items-center justify-between">
          <span className="text-[10px] text-slate-500">
            ProspectLens v1.0.0 • Diagnostic System
          </span>
          <button
            onClick={onClose}
            className="px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-lg text-xs font-semibold transition cursor-pointer"
          >
            Close Sandbox
          </button>
        </div>

      </div>
    </div>
  );
};
